apiVersion: extensions/v1beta1
#apiVersion: apps/v1beta2
#apiVersion: v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 5
  revisionHistoryLimit: 0
#  strategy:
#  type: RollingUpdate
#  rollingUpdate:
#    maxSurge: 1
#    maxUnavailable: 25%
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: iad.ocir.io/fedexoraclecloud/fsc/helloworld:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8484
#        readinessProbe:
#          httpGet:
#             path: /
#             port: 8484
#             initialDelaySeconds: 5
#             timeoutSeconds: 10
#             periodSeconds: 5
#             successThreshold: 1
      imagePullSecrets:  
      - name: satishocirsecret
