apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworldbluegreen-v2
  labels:
    app: helloworldbluegreen
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: helloworldbluegreen
  template:
    metadata:
      labels:
        app: helloworldbluegreen
    spec: 
      containers: 
      - name: helloworldbluegreen
        image: iad.ocir.io/fedexoraclecloud/fsc/helloworldbluegreen:latest
        resources:
         limits:
            cpu: 500m
         requests:
            cpu: 250m
        imagePullPolicy: Always
        ports:
        - containerPort: 8484
      imagePullSecrets:  
      - name: satishocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: helloworldbluegreen-green
  labels:
   name: helloworldbluegreen
  annotations:
   service.beta.kubernetes.io/oci-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8484
    protocol: TCP
  selector:
    app: helloworldbluegreen
