apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworldbluegreen
  labels:
    app: helloworldbluegreen
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: helloworldbluegreen
  template:
    metadata:
      labels:
        app: helloworldbluegreen
    spec: 
      containers: 
      - name: helloworldbluegreen
        image: iad.ocir.io/fedexoraclecloud/fsc/helloworldbluegreen:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8484
      imagePullSecrets:  
      - name: satishocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: helloworldbluegreen
  labels:
   name: helloworldbluegreen
  annotations:
   service.beta.kubernetes.io/oci-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8484
    protocol: TCP
  selector:
    app: helloworldbluegreen
---
apiVersion: autoscaling/v1
#apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworldbluegreenautoscaler
  namespace: satish-ns
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: helloworldbluegreen
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20   
status:
  currentReplicas: 1
  desiredReplicas: 1
