apiVersion: v1
kind: Service
metadata:
  name: helloworld
  annotations:
   service.beta.kubernetes.io/oci-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8484
    protocol: TCP
  selector:
    app: helloworld
